[package]
name = "bc-gatya-seeker"
version = "1.0.0"
edition = "2021"

[dependencies]


tokio = { version = "1.12", features = ["full"] }
reqwest = "0.11"
serde_json = "1.0"
rand = "0.8"
hmac = "0.12"
sha2 = "0.10"
hex = "0.4"
csv = "1.1"
chrono = "0.4"
